#!/bin/bash
now=$(date +"%m_%d_%Y_%T")
z=`ls -l /var/mail/root | awk '{print $5}'`
if [ "$z" -gt 2147483648 ]
then
echo "Size is more than 2GB"
echo "Going to Move the root file to root.bkp"
mv /var/mail/root /var/mail/root.$now &&
echo "moveing is completed. \ntar is going on"
tar -cvfz /var/mail/root.$now.tar.gz /var/mail/root.$now &&
echo "tar with zip is completed."
echo "completed :)"
else
echo "/var/log/root file size is not more than 2GB is $z"
fi
